version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./app/src:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:

